service: image-editor

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::*"

useDotenv: true

package:
  exclude:
    - README.md
    - .github/**
    - .idea/**

functions:
  processor:
    handler: handler.processor
    timeout: 59
    memorySize: 1536
    layers:
      - ${env:LAYER_IMAGE_MAGICK}
      - ${env:LAYER_GRAPHICSMAGICK}
